### ISSUE TITLE
expose revision_history_limit so we can change the default values.

### ISSUE THREAD

**Issue by therealrawal** [lacework/terraform-kubernetes-agent#32]
Hi, is it possible for us to change the revision_history_limit? I would like to change the default value.

**Comment by afiune** [comment]
Hello @sliide-jay 👋🏽 - We can absolutely enable an input so you can customize this field! We will work on
this new feature and notify you that it is ready to be used. We appreciate your feedback! 🎉

**Comment by afiune** [comment]
**JIRA:** https://lacework.atlassian.net/browse/ALLY-599

**Comment by therealrawal** [comment]
I have a brach ready if you allow me to push and create a PR.

**Comment by afiune** [comment]
Such a great initiative, @therealrawal !!! We would love for you to help us with this feature.

The way you can contribute is by forking this repository, making the modifications in your fork and
then, propose the change back to our repository. You can find this process at the following link:

* https://docs.github.com/en/get-started/quickstart/fork-a-repo

Something else to be aware of is the fact that we don't allow "[unsigned commits](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/about-commit-signature-verification)" in our open source
repositories, therefore you have to configure a GPG key to sign your commits, this is a security 
requirement that helps us ensure that your commits come from a trusted source. 

If you haven't done it already, you will have to:

1. [Generate a new GPG key](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/generating-a-new-gpg-key)
2. [Add a new GPG key to your GitHub account](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/adding-a-new-gpg-key-to-your-github-account)
3. [Tell Git about your signing key](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/telling-git-about-your-signing-key)
4. [Sign commits](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/signing-commits)

Please, let me know if you have problems with this process. Thank you so much in advance for your contribution! 🎉

**Comment by therealrawal** [comment]
https://github.com/lacework/terraform-kubernetes-agent/pull/33

fairly simple PR, let me know if i've missed anything.

**Comment by afiune** [comment]
@therealrawal Thank you so much for your contribution!! 🎉 I have reviewed the change and
it just needs a quick fix, after that we will merge and release 💯🙌🏽🥇

**Comment by therealrawal** [comment]
My bad! silly mistake, i've moved it under spec.

**Comment by afiune** [comment]
Preparing a release https://github.com/lacework/terraform-kubernetes-agent/pull/34
