### ISSUE TITLE
feat: add priorityClassName for kubernetes_daemonset resource

### ISSUE THREAD

**Issue by kris-savoy-truepill** [lacework/terraform-kubernetes-agent#47]
# Feature Request

**Describe the Feature Request**
The `lacework_datacollector` `kubernetes_daemonset` resource should support optional specification of `priorityClassName` in the template pod spec.

This would support Lacework's goal of providing continuous coverage and near-realtime reporting of anomalous activity on Kubernetes clusters where, for one reason or another, Lacework pods either need to evict other workloads or end up evicted themselves due to other workloads.

**Is your feature request related to a problem? Please describe**
It would be good if Laceworks coverage isn't subject to what other workloads are doing. We have some clusters where scheduling behavior results in a lack of full Lacework agent coverage for all nodes.

**Describe Preferred Solution**
The template pod spec could contain a dynamic block for variable specification of `priorityClassName` depending upon a new input variable.

Highlighting priority class specification in supporting integrations-related documentation that use this module would also be useful to ensure customers don't lose insight into critical events happening in their environment(s).

**Additional Context**
N/A

**Comment by hazedav** [comment]
@[kris-savoy-truepill](https://github.com/kris-savoy-truepill),

Thanks for producing this feature request.  Just wanted to give you a heads up that I've opened a JIRA ticket internally for tracking this enhancement (https://lacework.atlassian.net/browse/ALLY-991) and we will evaluate the request during our next sprint planning.

David

**Comment by kris-savoy-truepill** [comment]
@hazedav  - thanks for the fast acknowledgement!

I'd issue a PR myself, but we've got a few different approaches we may use to manage the workload internally on our end (not all being Terraform). For instance, we may consider using the lacework-agent Helm chart instead, which already supports this:
https://github.com/lacework/helm-charts/blob/main/lacework-agent/templates/daemonset.yaml#L34-L36
